"""
Configuration module
전역 설정값을 제공합니다.
"""

from config.settings import (
    # YOLO 모델 경로
    MODELS_DIR,
    MODEL_PATH,
    WASTE_MODEL_PATH,
    WASTE_MODEL_HF_ID,
    OBB_MODEL_PATH,
    # YOLO 설정
    CONFIDENCE_THRESHOLD,
    IOU_THRESHOLD,
    # 이상 감지 설정
    MOVEMENT_THRESHOLD,
    ASPECT_RATIO_THRESHOLD,
    TRACKING_IOU_THRESHOLD,
    MAX_DISAPPEARED_FRAMES,
    # 카메라 설정
    CAMERA_SOURCE,
    FRAME_WIDTH,
    FRAME_HEIGHT,
    FPS_LIMIT,
    # UART 설정
    UART_PORT,
    UART_BAUDRATE,
    UART_TIMEOUT,
    UART_ENABLED,
    # 로깅 설정
    LOG_LEVEL,
    LOG_TO_FILE,
    LOG_FILE_PATH,
    LOG_MAX_BYTES,
    LOG_BACKUP_COUNT,
    # 시각화 설정
    ENABLE_VISUALIZATION,
    WINDOW_NAME,
    COLOR_NORMAL,
    COLOR_MOVEMENT,
    COLOR_COLLISION,
    # 시스템 설정
    AUTO_DOWNLOAD_MODEL,
    SHOW_FPS,
    SHOW_DETECTION_COUNT,
)

__all__ = [
    "MODELS_DIR",
    "MODEL_PATH",
    "WASTE_MODEL_PATH",
    "WASTE_MODEL_HF_ID",
    "OBB_MODEL_PATH",
    "CONFIDENCE_THRESHOLD",
    "IOU_THRESHOLD",
    "MOVEMENT_THRESHOLD",
    "ASPECT_RATIO_THRESHOLD",
    "TRACKING_IOU_THRESHOLD",
    "MAX_DISAPPEARED_FRAMES",
    "CAMERA_SOURCE",
    "FRAME_WIDTH",
    "FRAME_HEIGHT",
    "FPS_LIMIT",
    "UART_PORT",
    "UART_BAUDRATE",
    "UART_TIMEOUT",
    "UART_ENABLED",
    "LOG_LEVEL",
    "LOG_TO_FILE",
    "LOG_FILE_PATH",
    "LOG_MAX_BYTES",
    "LOG_BACKUP_COUNT",
    "ENABLE_VISUALIZATION",
    "WINDOW_NAME",
    "COLOR_NORMAL",
    "COLOR_MOVEMENT",
    "COLOR_COLLISION",
    "AUTO_DOWNLOAD_MODEL",
    "SHOW_FPS",
    "SHOW_DETECTION_COUNT",
]
